//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_seferler
    {
        public int id { get; set; }
        public string Nereden { get; set; }
        public string Nereye { get; set; }
        public Nullable<int> koltuk { get; set; }
        public Nullable<int> soforID { get; set; }
        public string Tarih { get; set; }
    }
}
