//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sube2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GorselProgramlamaEntities : DbContext
    {
        public GorselProgramlamaEntities()
            : base("name=GorselProgramlamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_bilgiler> tbl_bilgiler { get; set; }
        public virtual DbSet<tbl_kisisel> tbl_kisisel { get; set; }
        public virtual DbSet<tbl_kisisel3> tbl_kisisel3 { get; set; }
        public virtual DbSet<tbl_kisisel2> tbl_kisisel2 { get; set; }
        public virtual DbSet<tbl_kisibilgileri> tbl_kisibilgileri { get; set; }
    }
}
