//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vize
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjeEntities : DbContext
    {
        public ProjeEntities()
            : base("name=ProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_biletler> tbl_biletler { get; set; }
        public virtual DbSet<tbl_Kullanicilar> tbl_Kullanicilar { get; set; }
        public virtual DbSet<tbl_otubusler> tbl_otubusler { get; set; }
        public virtual DbSet<tbl_seferler> tbl_seferler { get; set; }
        public virtual DbSet<tbl_soforler> tbl_soforler { get; set; }
    }
}
