//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_otubusler
    {
        public int id { get; set; }
        public string otubusAdi { get; set; }
        public Nullable<int> Koltuk { get; set; }
    }
}
