//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_biletler
    {
        public int id { get; set; }
        public Nullable<int> seferid { get; set; }
        public string Ad { get; set; }
        public string SoyAd { get; set; }
        public string TC { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> koltukNO { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
